spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:db_news}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:FF1rfiMRIqj-jDnGkbpAtMBrt5bGDGegooIkXMGtZ17uaVtuqGAv0rJJSpDN88Rxn21ctIDkZCNr1qBU_ALSYQ==}
    expiration-hours: ${JWT_EXPIRATION_HOURS:8}
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
