CREATE TABLE IF NOT EXISTS news (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

INSERT INTO news (title, content, created_at)
SELECT t.title, t.content, t.created_at FROM (VALUES
-- Tecnologia & Inovação
('Inteligência Artificial revoluciona diagnóstico médico', 'Novos modelos de IA estão auxiliando médicos a identificar doenças raras com maior precisão.', NOW() - INTERVAL '1 day'),
('Avanços na computação quântica superam expectativas', 'Pesquisadores alcançaram um novo marco de estabilidade em qubits funcionais.', NOW() - INTERVAL '2 days'),
('O futuro da energia solar com novos painéis de perovskita', 'Células solares híbridas alcançam eficiência recorde na conversão de luz em eletricidade.', NOW() - INTERVAL '3 days'),
('Veículos autônomos iniciam testes em grandes capitais', 'Empresas de mobilidade expandem os testes de táxis sem motorista para novas rotas urbanas.', NOW() - INTERVAL '4 days'),
('Novo padrão de Wi-Fi promete conexões ultra-rápidas', 'O padrão Wi-Fi 7 começa a ser adotado por grandes fabricantes de roteadores.', NOW() - INTERVAL '5 days'),
('Linguagens de programação mais populares do ano', 'Levantamento aponta crescimento contínuo de Python, Rust e TypeScript no ecossistema global.', NOW() - INTERVAL '6 days'),
('Baterias de estado sólido entram em fase de produção', 'Tecnologia promete dobrar a autonomia de carros elétricos e reduzir tempo de recarga.', NOW() - INTERVAL '7 days'),
('Cibersegurança: aumento de ataques exige novas defesas', 'Empresas investem pesado em arquitetura Zero Trust para proteger redes corporativas.', NOW() - INTERVAL '8 days'),
('Impressionante avanço na robótica humanoide', 'Robôs bípedes demonstram habilidades motoras avançadas em tarefas domésticas complexas.', NOW() - INTERVAL '9 days'),
('Adoção do ecossistema Open Source bate recordes', 'Grandes corporações impulsionam o financiamento de projetos comunitários essenciais.', NOW() - INTERVAL '10 days'),
('Redes 6G começam a ser desenvolvidas por consórcios', 'Expectativa é de conectividade terabit por segundo até o final da década.', NOW() - INTERVAL '11 days'),
('Avanços em visão computacional facilitam a logística', 'Armazéns inteligentes utilizam câmeras para triagem e checagem de estoque automatizada.', NOW() - INTERVAL '12 days'),
('Microprocessadores com arquitetura RISC-V ganham espaço', 'A arquitetura aberta ganha mercado em dispositivos IoT e automação industrial.', NOW() - INTERVAL '13 days'),
('Tecnologia Wearable foca na prevenção de problemas cardíacos', 'Smartwatches utilizam sensores ópticos para rastrear arritmias em tempo real.', NOW() - INTERVAL '14 days'),
('Impressão 3D de órgãos humanos avança na biomedicina', 'Cientistas conseguem imprimir estruturas vasculares funcionais em laboratório.', NOW() - INTERVAL '15 days'),
('Edge computing reduz latência em aplicações críticas', 'Processamento próximo ao usuário acelera respostas em indústrias e cidades inteligentes.', NOW() - INTERVAL '16 days'),
('Chatbots conversacionais transformam o atendimento ao cliente', 'Empresas adotam assistentes virtuais capazes de resolver demandas complexas por conta própria.', NOW() - INTERVAL '17 days'),
('Realidade aumentada redefine os treinamentos corporativos', 'Simulações imersivas reduzem custos e aumentam a retenção de aprendizado.', NOW() - INTERVAL '18 days'),
('Armazenamento em nuvem híbrida ganha preferência', 'Empresas equilibram custo e segurança entre ambientes públicos e privados.', NOW() - INTERVAL '19 days'),
('Blockchain avança além das criptomoedas', 'Tecnologia de registros distribuídos ganha uso em rastreamento de cadeias de suprimento.', NOW() - INTERVAL '20 days'),
('Processadores com litografia de 2 nanômetros entram em teste', 'Chips mais eficientes prometem reduzir o consumo energético dos data centers.', NOW() - INTERVAL '21 days'),
('Sensores inteligentes monitoram plantações em tempo real', 'Agricultura de precisão reduz desperdício de água e insumos.', NOW() - INTERVAL '22 days'),
('Plataformas de low-code aceleram o desenvolvimento de apps', 'Times não técnicos criam soluções internas em dias em vez de meses.', NOW() - INTERVAL '23 days'),
('Carregamento sem fio ganha potência para notebooks', 'Novos padrões permitem carregar laptops e tablets sem cabos.', NOW() - INTERVAL '24 days'),
('Assistentes de código baseados em IA aumentam produtividade', 'Desenvolvedores relatam ganho de velocidade na escrita de testes e funções.', NOW() - INTERVAL '25 days'),
-- Ciência & Saúde
('Cientistas identificam novo biomarcador para Alzheimer', 'Exame de sangue promete diagnosticar a doença anos antes dos primeiros sintomas.', NOW() - INTERVAL '26 days'),
('Missão espacial coleta amostras de asteroide com sucesso', 'Material primitivo pode revelar segredos da formação do sistema solar.', NOW() - INTERVAL '27 days'),
('Vacina de mRNA mostra eficácia contra novas variantes', 'Imunizante adaptado gera resposta robusta em testes clínicos de fase avançada.', NOW() - INTERVAL '28 days'),
('Descoberto novo exoplaneta na zona habitável', 'Telescópio espacial detectou planeta rochoso com possibilidade de água líquida.', NOW() - INTERVAL '29 days'),
('Pesquisa revela benefícios do jejum intermitente', 'Estudo aponta melhoras no metabolismo e na saúde cardiovascular.', NOW() - INTERVAL '30 days'),
('Terapia genética cura doença hereditária rara', 'Pacientes tratados apresentam remissão completa após tratamento experimental.', NOW() - INTERVAL '31 days'),
('Oceanos mais quentes aceleram derretimento de geleiras', 'Dados de satélite mostram elevação recorde no nível dos mares.', NOW() - INTERVAL '32 days'),
('Nova técnica de edição genética melhora precisão', 'Ferramenta ampliada reduz efeitos colaterais indesejados em células humanas.', NOW() - INTERVAL '33 days'),
('Cientistas criam músculo artificial biocompatível', 'Material pode futuramente substituir tecidos danificados cirurgicamente.', NOW() - INTERVAL '34 days'),
('Exames de retina permitem detectar sinais de diabetes', 'Inteligência artificial analisa imagens do fundo do olho em segundos.', NOW() - INTERVAL '35 days'),
('Pesquisadores avançam na criação de biocombustíveis', 'Algas modificadas podem dobrar a produção de etanol sustentável.', NOW() - INTERVAL '36 days'),
('Estudo aponta que exercício físico reduz risco de demência', 'Atividade regular estimula a saúde de áreas ligadas à memória.', NOW() - INTERVAL '37 days'),
('Foguete reutilizável completa centésimo lançamento', 'Marco reduz drasticamente o custo do acesso ao espaço.', NOW() - INTERVAL '38 days'),
('Novo antibiótico combate bactérias super-resistentes', 'Composto sintético mostrou eficácia em testes com infecções hospitalares.', NOW() - INTERVAL '39 days'),
('Telescópio captura imagem inédita de buraco negro supermassivo', 'Registro ajuda a entender a dinâmica da matéria em gravidade extrema.', NOW() - INTERVAL '40 days'),
('Probióticos personalizados melhoram a saúde intestinal', 'Novos estudos relacionam equilíbrio da flora a bem-estar geral.', NOW() - INTERVAL '41 days'),
('Robôs cirúrgicos ganham precisão com visão 3D', 'Procedimentos minimamente invasivos reduzem tempo de recuperação.', NOW() - INTERVAL '42 days'),
('Descoberta ajuda a entender a origem da vida na Terra', 'Moléculas orgânicas complexas foram detectadas em meteoritos antigos.', NOW() - INTERVAL '43 days'),
('Novos mapas cerebrais revelam redes da memória', 'Neurocientistas mapeiam conexões que formam lembranças de longo prazo.', NOW() - INTERVAL '44 days'),
('Estudo liga má qualidade do sono a doenças cardíacas', 'Pesquisadores recomendam rotina fixa para reduzir riscos.', NOW() - INTERVAL '45 days'),
('Energia de fusão alcança novo recorde de reação', 'Reator experimental sustentou plasma por tempo inédito.', NOW() - INTERVAL '46 days'),
('Plásticos biodegradáveis ganham força na indústria', 'Novo material se decompõe em meses sem deixar microplásticos.', NOW() - INTERVAL '47 days'),
('Cientistas decodificam genoma de planta medicinal', 'Descoberta pode acelerar criação de fármacos naturais.', NOW() - INTERVAL '48 days'),
('Estação espacial conclui nova montagem de painéis solares', 'Estrutura amplia capacidade energética do laboratório orbital.', NOW() - INTERVAL '49 days'),
('Inteligência artificial prevê terremotos secundários', 'Modelos analisam réplicas para estimar áreas de maior risco.', NOW() - INTERVAL '50 days'),
-- Economia & Negócios
('Mercado de tecnologia atrai recorde de investimentos', 'Fundos de venture capital aplicam bilhões em startups de IA.', NOW() - INTERVAL '51 days'),
('Criptomoedas oscilam com novas regulações no setor', 'Bancos centrais sinalizam marco regulatório para ativos digitais.', NOW() - INTERVAL '52 days'),
('Comércio eletrônico cresce 20% no último trimestre', 'Consumidores migram cada vez mais para compras online no varejo.', NOW() - INTERVAL '53 days'),
('Empresas adotam semana de trabalho reduzida', 'Pilotos mostram aumento de produtividade e satisfação dos funcionários.', NOW() - INTERVAL '54 days'),
('Setor de energia renovável cria novos empregos', 'Expansão eólica e solar supera contratações nas fontes tradicionais.', NOW() - INTERVAL '55 days'),
('Agronegócio digitaliza operações com drones', 'Tecnologia reduz custos e aumenta a eficiência das colheitas.', NOW() - INTERVAL '56 days'),
('Bancos digitais ultrapassam agências tradicionais em clientes', 'Fintechs conquistam público jovem com tarifas reduzidas.', NOW() - INTERVAL '57 days'),
('Turismo internacional se recupera em ritmo acelerado', 'Destinos voltam a registrar ocupação recorde em alta temporada.', NOW() - INTERVAL '58 days'),
('Automação reduz empregos, mas cria novas funções', 'Relatório aponta demanda crescente por especialistas em dados.', NOW() - INTERVAL '59 days'),
('Preço de alimentos estabiliza após safra recorde', 'Colheita abundante alivia a inflação em diversas regiões.', NOW() - INTERVAL '60 days'),
('Startups de saúde atraem investidores globais', 'Telemedicina e monitoramento remoto lideram captação de recursos.', NOW() - INTERVAL '61 days'),
('Indústria automotiva acelera transição para elétricos', 'Montadoras anunciam novos modelos e fábricas dedicadas.', NOW() - INTERVAL '62 days'),
('Pequenas empresas lideram contratação no país', 'Setor de serviços responde pela maioria das novas vagas.', NOW() - INTERVAL '63 days'),
('Logística verde reduz custos e emissões', 'Frotas elétricas e rotas otimizadas ganham espaço nas entregas.', NOW() - INTERVAL '64 days'),
('Mercado de imóveis comerciais se reinventa', 'Espaços híbridos ganham preferência após trabalho remoto.', NOW() - INTERVAL '65 days'),
('Comércio internacional registra novo superávit', 'Exportações de commodities e manufaturados crescem no semestre.', NOW() - INTERVAL '66 days'),
('Fintechs facilitam crédito para pequenos negócios', 'Plataformas digitais reduzem burocracia e taxas de juros.', NOW() - INTERVAL '67 days'),
('Setor de games movimenta bilhões no país', 'Crescimento do mercado atrai grandes desenvolvedoras globais.', NOW() - INTERVAL '68 days'),
('Franchising cresce apoiado em transformação digital', 'Redes investem em apps e gestão inteligente de operações.', NOW() - INTERVAL '69 days'),
('Economia circular reduz desperdício na indústria', 'Empresas reaproveitam materiais e economizam recursos.', NOW() - INTERVAL '70 days'),
('Exportação de software brasileiro atinge recorde', 'Empresas locais conquistam mercados na América Latina e Europa.', NOW() - INTERVAL '71 days'),
('Varejo aposta em experiência omnichannel', 'Integração entre lojas físicas e digitais melhora o atendimento.', NOW() - INTERVAL '72 days'),
('Novo programa incentiva inovação em pequenas cidades', 'Editais financiam projetos de impacto local com tecnologia.', NOW() - INTERVAL '73 days'),
('Mercado de trabalho remoto cruza fronteiras', 'Profissionais brasileiros assumem vagas em empresas estrangeiras.', NOW() - INTERVAL '74 days'),
('Previsão aponta crescimento do PIB acima do esperado', 'Economistas revisam para cima as projeções para o ano.', NOW() - INTERVAL '75 days'),
-- Esportes & Cultura
('Seleção nacional vence torneio e levanta a taça', 'Equipe encerra campanha invicta com gol no último minuto.', NOW() - INTERVAL '76 days'),
('Atleta brasileiro quebra recorde mundial de velocidade', 'Marca histórica consagra nova geração do atletismo nacional.', NOW() - INTERVAL '77 days'),
('Festival de cinema nacional bate público recorde', 'Edição deste ano exibiu mais de trezentos filmes brasileiros.', NOW() - INTERVAL '78 days'),
('Clube anuncia contratação de atacante estrela', 'Reforço de peso chega para disputar o próximo campeonato.', NOW() - INTERVAL '79 days'),
('Maratona de São Paulo reúne milhares de corredores', 'Evento contou com esquema especial de trânsito e hidratação.', NOW() - INTERVAL '80 days'),
('Exposição de arte imersiva atrai novos públicos', 'Mostra interativa combina projeções e realidade aumentada.', NOW() - INTERVAL '81 days'),
('Campeonato de e-sports cresce em audiência', 'Final transmitida online superou recordes de espectadores.', NOW() - INTERVAL '82 days'),
('Orquestra sinfônica encanta plateia com concerto gratuito', 'Apresentação ao ar livre reuniu famílias no parque central.', NOW() - INTERVAL '83 days'),
('Novo museu de ciências abre as portas ao público', 'Espaço interativo promete despertar interesse de crianças e adultos.', NOW() - INTERVAL '84 days'),
('Atleta paralímpico conquista medalha de ouro', 'Vitória emocionante marca superação e dedicação do esportista.', NOW() - INTERVAL '85 days'),
('Série nacional conquista prêmio internacional', 'Produção brasileira é reconhecida em festival de televisão.', NOW() - INTERVAL '86 days'),
('Ciclovia ampliada incentiva uso de bicicleta na cidade', 'Novo trecho conecta bairros e reduz tempo de deslocamento.', NOW() - INTERVAL '87 days'),
('Gravadora lança álbum com músicos da nova geração', 'Trabalho mistura ritmos regionais com produção moderna.', NOW() - INTERVAL '88 days'),
('Time de vôlei feminino vence campeonato continental', 'Conquista garante vaga no torneio mundial do próximo ano.', NOW() - INTERVAL '89 days'),
('Peça de teatro inovadora usa inteligência artificial no palco', 'Produção experimental combina atores e projeções interativas.', NOW() - INTERVAL '90 days'),
('Basquete local promove torneio de inclusão social', 'Projeto une esporte e educação para jovens de periferia.', NOW() - INTERVAL '91 days'),
('Livro de autor brasileiro lidera lista de mais vendidos', 'Romance conquista leitores e é traduzido para diversos idiomas.', NOW() - INTERVAL '92 days'),
('Escola de samba apresenta enredo sobre preservação ambiental', 'Desfile do próximo carnaval promete mensagem de consciência ecológica.', NOW() - INTERVAL '93 days'),
('Tenista nacional avança à semifinal de grande torneio', 'Vitória de virada garante vaga entre os quatro melhores.', NOW() - INTERVAL '94 days'),
('Festival gastronômico reúne chefs premiados', 'Evento celebra a diversidade da culinária regional.', NOW() - INTERVAL '95 days'),
('Maratonista amadora inspira geração após vitória surpreendente', 'História de dedicação viraliza e motiva novos corredores.', NOW() - INTERVAL '96 days'),
('Exposição fotográfica documenta mudanças na paisagem urbana', 'Acervo reúne imagens históricas de décadas passadas.', NOW() - INTERVAL '97 days'),
('Campeonato estadual de xadrez atrai jovens talentos', 'Competição revela novos nomes do esporte da mente.', NOW() - INTERVAL '98 days'),
('Banda independente ganha destaque em plataformas digitais', 'Som autoral alcança milhões de reproduções em poucas semanas.', NOW() - INTERVAL '99 days'),
('Novo parque esportivo inaugura com quadras modernas', 'Espaço gratuito oferece atividades para todas as idades.', NOW() - INTERVAL '100 days')
) AS t(title, content, created_at)
WHERE NOT EXISTS (SELECT 1 FROM news);